name: Rebuild Bundles on Milkdown Crepe Update

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: ncu -u --target latest "@milkdown/kit"

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Stage changes
        run: |
          git add package.json package-lock.json dist/

      - name: Check for changes
        id: git_status
        run: |
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Get new version from package.json
        if: env.changes == 'true'
        id: get_version
        run: |
          NEW_VERSION=$(jq -r '.dependencies["@milkdown/kit"]' package.json | tr -d '^')
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "Extracted new version: $NEW_VERSION" # Log the extracted version

      - name: Update package.json version
        if: env.changes == 'true'
        run: |
          npm version ${{ env.new_version }} --no-git-tag-version
        id: update_version

      - name: Organize dist files
        if: env.changes == 'true'
        run: |
          BUNDLE_NAME="milkdown-kit-bundle"
          SOURCE_BUNDLE_PATH="dist/$BUNDLE_NAME.umd.js"
          VERSIONED_DIR="dist/${{ env.new_version }}"
          VERSIONED_BUNDLE_JS="$VERSIONED_DIR/$BUNDLE_NAME-${{ env.new_version }}.js"
          VERSIONED_BUNDLE_MIN_JS="$VERSIONED_DIR/$BUNDLE_NAME-${{ env.new_version }}.min.js"
          LATEST_DIR="dist/latest"
          LATEST_BUNDLE_JS="$LATEST_DIR/$BUNDLE_NAME.js"
          LATEST_BUNDLE_MIN_JS="$LATEST_DIR/$BUNDLE_NAME.min.js"

          # Create versioned directory
          mkdir -p $VERSIONED_DIR

          # Copy bundle to versioned directory
          cp $SOURCE_BUNDLE_PATH $VERSIONED_BUNDLE_JS

          # Create minified version and save to versioned directory
          npx terser $SOURCE_BUNDLE_PATH -o $VERSIONED_BUNDLE_MIN_JS --compress --mangle

          # Create a 'latest' directory for easy access
          rm -rf $LATEST_DIR
          mkdir -p $LATEST_DIR

          # Copy versioned files to latest directory
          cp $VERSIONED_BUNDLE_MIN_JS $LATEST_BUNDLE_MIN_JS
          cp $VERSIONED_BUNDLE_JS $LATEST_BUNDLE_JS

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "build: update @milkdown/kit to v${{ env.new_version }} and rebuild"
          git push

      - name: Create and push version tag
        if: env.changes == 'true'
        run: |
          git tag v${{ env.new_version }}
          git push origin v${{ env.new_version }}

      - name: Update latest tag
        if: env.changes == 'true'
        run: |
          git tag -f latest
          git push -f origin latest
